# Generated by Django 5.0.7 on 2024-08-07 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0005_alter_image_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
