# Generated by Django 5.0.7 on 2025-01-17 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0014_alter_place_title'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='place',
            unique_together={('lng', 'lat')},
        ),
    ]
